# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-23 23:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GerenciarDoenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doenca', models.CharField(max_length=100)),
                ('codigo', models.IntegerField()),
                ('gravidade', models.CharField(max_length=250)),
                ('descricao', models.CharField(max_length=250)),
                ('sintomas', models.CharField(max_length=250)),
                ('propagacao', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000, null=True)),
                ('from_adm', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrgaosSaude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cnpj', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=50)),
                ('autarquia', models.CharField(max_length=15)),
                ('sigla', models.CharField(max_length=8)),
                ('rua', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('pais', models.CharField(max_length=50)),
                ('cep', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RelatarDoenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=150)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitarDoenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doenca', models.CharField(max_length=100)),
                ('codigo', models.IntegerField()),
                ('gravidade', models.CharField(max_length=250)),
                ('descricao', models.CharField(max_length=250)),
                ('sintomas', models.CharField(max_length=250)),
                ('propagacao', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
