# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-07 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='configAcessibilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alto_contraste', models.IntegerField(default=0)),
                ('tamanho_da_fonte', models.IntegerField(default=0)),
                ('baixo_risco', models.IntegerField(default=1)),
                ('alta_gravidade', models.IntegerField(default=1)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
