# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 02:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_pedidoslogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatardoenca',
            name='nome',
        ),
        migrations.AddField(
            model_name='relatardoenca',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 6, 21, 2, 30, 19, 571488, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatardoenca',
            name='doenca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.GerenciarDoenca'),
            preserve_default=False,
        ),
    ]
